/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GuiAcademia;

import java.awt.Image;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import LogicaAcademia.logicaAlumnos;
import factoryDAO.DaoFactory;
import interfaceIDao.IDao;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelosAcademia.Alumno;
import modelosDaos.AlumnoDao;

/**
 *
 * @author lfelipeh
 */
public class FormularioAlumnos extends javax.swing.JFrame {

    /**
     * Creates new form GestionAlumnos
     */
    public FormularioAlumnos() {
        initComponents();
        setLabelImage();
    }

    private void setLabelImage() {

        //ESTE CODIGO SE IMPLEMENTA CUANDO CREE EL JLABELIMAGE EN DESIGN.
        Image img1 = Toolkit.getDefaultToolkit().createImage("/home/lfelipeh/Documentos/AD2-DAM/NetBeansProjects/AcademiaPatronDAO1/src/GuiAcademia/images/logo-itaca.jpg");
        img1 = img1.getScaledInstance(jLabelImage.getWidth(), jLabelImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon img2 = new ImageIcon(img1);
        jLabelImage.setIcon(img2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelDNI = new javax.swing.JLabel();
        jTextFieldDNI = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelSurname = new javax.swing.JLabel();
        jTextFieldSurname = new javax.swing.JTextField();
        jLabelLocation = new javax.swing.JLabel();
        jTextFieldLocation = new javax.swing.JTextField();
        jLabelBirth = new javax.swing.JLabel();
        jTextFieldBirth = new javax.swing.JTextField();
        jLabelZipCode = new javax.swing.JLabel();
        jTextFieldZipCode = new javax.swing.JTextField();
        jLabelNumberT = new javax.swing.JLabel();
        jTextFieldNumberT = new javax.swing.JTextField();
        jLabelHeader = new javax.swing.JLabel();
        jLabelImage = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setForeground(new java.awt.Color(0, 255, 0));

        jPanel1.setLayout(new java.awt.GridLayout(8, 2));

        jLabelID.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelID.setText("Introduzca el Id del alumno: (Número Entero)");
        jPanel1.add(jLabelID);
        jPanel1.add(jTextFieldID);

        jLabelDNI.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelDNI.setText("Introduzca el dni del alumno: (Cadena Texto)");
        jPanel1.add(jLabelDNI);
        jPanel1.add(jTextFieldDNI);

        jLabelName.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelName.setText("Introduzca el nombre del alumno: (Cadena Texto)");
        jPanel1.add(jLabelName);
        jPanel1.add(jTextFieldName);

        jLabelSurname.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelSurname.setText("Introduzca el apellido del alumno: (Cadena Texto)");
        jPanel1.add(jLabelSurname);
        jPanel1.add(jTextFieldSurname);

        jLabelLocation.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelLocation.setText(" Introduzca la direccion del alumno: (Cadena Texto)");
        jPanel1.add(jLabelLocation);
        jPanel1.add(jTextFieldLocation);

        jLabelBirth.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelBirth.setText("Introduzca la fecha de nacimiento:  (Cadena Texto)");
        jPanel1.add(jLabelBirth);
        jPanel1.add(jTextFieldBirth);

        jLabelZipCode.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelZipCode.setText("Introduzca el codigo postal: (Número Entero)");
        jPanel1.add(jLabelZipCode);
        jPanel1.add(jTextFieldZipCode);

        jLabelNumberT.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelNumberT.setText("Introduzca el teléfono del alumno: (Cadena Texto)");
        jPanel1.add(jLabelNumberT);
        jPanel1.add(jTextFieldNumberT);

        jLabelHeader.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabelHeader.setForeground(new java.awt.Color(0, 153, 0));
        jLabelHeader.setText("GESTIÓN ALUMNOS IES ÍTACA 2 DESARROLLO APLICACIONES MULTIPLATAFORMA");

        jButtonSubmit.setBackground(new java.awt.Color(0, 153, 0));
        jButtonSubmit.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jButtonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubmit.setText("Agregar Alumno");
        jButtonSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(363, 363, 363))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:
        RegistroAlumnos plantillaBD;
        try {
            // Primero validamos los campos
            if (jTextFieldID.getText().isEmpty() || !jTextFieldID.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID válido (solo números).", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (jTextFieldDNI.getText().isEmpty() || jTextFieldName.getText().isEmpty() || jTextFieldSurname.getText().isEmpty()
                    || jTextFieldLocation.getText().isEmpty() || jTextFieldBirth.getText().isEmpty() || jTextFieldZipCode.getText().isEmpty()
                    || jTextFieldNumberT.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Confirmar antes de agregar el alumno
            int confirmation = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea agregar este alumno?",
                    "Confirmar ingreso", JOptionPane.YES_NO_OPTION);

            if (confirmation == JOptionPane.YES_OPTION) {
                // Crear el objeto Alumno con los datos proporcionados
                Alumno alumnoItaca = new Alumno();
                alumnoItaca.setId_alumno(Integer.valueOf(jTextFieldID.getText()));
                alumnoItaca.setDni_alumno(jTextFieldDNI.getText());
                alumnoItaca.setNombre_alumno(jTextFieldName.getText());
                alumnoItaca.setApellido_alumno(jTextFieldSurname.getText());
                alumnoItaca.setDireccion_alumno(jTextFieldLocation.getText());
                alumnoItaca.setFecha_nacimiento(jTextFieldBirth.getText());
                alumnoItaca.setCodPostal_alumno(Integer.valueOf(jTextFieldZipCode.getText()));
                alumnoItaca.setTelefono_alumno(jTextFieldNumberT.getText());

                // Llamar a la lógica para agregar el alumno
                logicaAlumnos.agregarAlumno(alumnoItaca);

                // Crear el registro en la base de datos
                IDao daoAlumno = DaoFactory.getDaoType(DaoFactory.Daotype.ALUMNO);
                daoAlumno.crearRegistro(alumnoItaca);

                // Confirmación de éxito
                JOptionPane.showMessageDialog(this, "El Alumno se ha ingresado correctamente a la base de datos.", "", JOptionPane.INFORMATION_MESSAGE);
                System.out.println("Se ha agregado correctamente el Alumno en la base de datos del IES ÍTACA.");

                // Deshabilitar el botón y cerrar el formulario
                jButtonSubmit.setEnabled(true);
                this.dispose();
            }
        } catch (Exception ex) {
            Logger.getLogger(FormularioAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabelBirth;
    private javax.swing.JLabel jLabelDNI;
    private javax.swing.JLabel jLabelHeader;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelLocation;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNumberT;
    private javax.swing.JLabel jLabelSurname;
    private javax.swing.JLabel jLabelZipCode;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBirth;
    private javax.swing.JTextField jTextFieldDNI;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldLocation;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNumberT;
    private javax.swing.JTextField jTextFieldSurname;
    private javax.swing.JTextField jTextFieldZipCode;
    // End of variables declaration//GEN-END:variables
}
